import type { DestinationCard } from "./types";

export const destinations: DestinationCard[] = [
  {
    slug: "islandia",
    title: "Islandia",
    region: "Europa del Norte",
    subtitle: "Auroras boreales, glaciares y el roadtrip más épico del planeta.",
    tag: "Top destino",
    priceFrom: "desde $84,890 MXN",
    highlight: "Luna de miel · Aventura",
    imageSrc: "/images/destinos/islandia.jpg",
    imageAlt: "Auroras boreales sobre Islandia",
  },
  {
    slug: "japon",
    title: "Japón",
    region: "Asia",
    subtitle: "Tokio, Kioto, Osaka — la cultura más fascinante del mundo.",
    tag: "Nuevo",
    priceFrom: "desde $90,890 MXN",
    highlight: "Cultura · Gastronomía",
    imageSrc: "/images/destinos/japon.jpg",
    imageAlt: "Templo japonés entre cerezos en flor",
  },
  {
    slug: "europa",
    title: "Europa a tu ritmo",
    region: "Europa",
    subtitle: "París, Roma, Barcelona — rutas con lógica, sin regresos innecesarios.",
    priceFrom: "desde $85,000 MXN",
    highlight: "Parejas · Amigos",
    imageSrc: "/images/destinos/europa.jpg",
    imageAlt: "Vista panorámica de una ciudad europea",
    href: "https://wa.me/5218716887385?text=Hola%20Flymingo!%20Me%20interesa%20un%20viaje%20a%20Europa%20%F0%9F%8C%8D%20%C2%BFpueden%20cotizarme%3F",
  },
  {
    slug: "grecia",
    title: "Grecia",
    region: "Mediterráneo",
    subtitle: "Santorini, Mykonos y el azul más bonito que verás en tu vida.",
    priceFrom: "desde $89,000 MXN",
    highlight: "Luna de miel · Playas",
    imageSrc: "/images/destinos/grecia.jpg",
    imageAlt: "Casas blancas de Santorini frente al mar",
    href: "https://wa.me/5218716887385?text=Hola%20Flymingo!%20Me%20interesa%20un%20viaje%20a%20Grecia%20%F0%9F%87%AC%F0%9F%87%B7%20%C2%BFpueden%20cotizarme%3F",
  },
  {
    slug: "nueva-york",
    title: "Nueva York",
    region: "América del Norte",
    subtitle: "La ciudad que no duerme, a tu estilo y a tu ritmo.",
    priceFrom: "desde $42,000 MXN",
    highlight: "Cultura · Shopping",
    imageSrc: "/images/destinos/nueva-york.jpg",
    imageAlt: "Skyline de Nueva York al atardecer",
    href: "https://wa.me/5218716887385?text=Hola%20Flymingo!%20Me%20interesa%20un%20viaje%20a%20Nueva%20York%20%F0%9F%97%BD%EF%B8%8F%20%C2%BFpueden%20cotizarme%3F",
  },
  {
    slug: "maldivas",
    title: "Maldivas",
    region: "Océano Índico",
    subtitle: "Overwater bungalows y el turquesa más puro que existe.",
    tag: "Luxe",
    priceFrom: "Cotizar",
    highlight: "Luna de miel · Lujo",
    imageSrc: "/images/destinos/maldivas.jpg",
    imageAlt: "Bungalow sobre el agua turquesa en Maldivas",
    href: "https://wa.me/5218716887385?text=Hola%20Flymingo!%20Me%20interesa%20un%20viaje%20a%20Maldivas%20%F0%9F%8F%9D%EF%B8%8F%20%C2%BFpueden%20cotizarme%3F",
  },
];
